INSERT INTO collections (name, slug, description, active, image_url, display_position, display_order, target_audience)
VALUES
-- Women collections
('Coleção Verão 26', 'colecao-verao-26-1', 'Descubra a vibração e o frescor da nova Coleção Verão 26. Peças exclusivas criadas para oferecer o máximo de conforto sem abrir mão da sofisticação nos dias mais quentes.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784638354/ver%C3%A3o-2026-feminino_lz5o9q.jpg', 'HEADER', 1, 'WOMEN'),
('Inverno Elegante', 'inverno-elegante-2', 'Sinta o aconchego e a classe do Inverno Elegante. Uma seleção rigorosa de tecidos nobres para manter você aquecida com muito estilo.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784638353/inverno-elegante-feminino_yuclvi.jpg', 'NEW_ARRIVALS', 2, 'WOMEN'),
('Básicos Essenciais', 'basicos-essenciais-3', 'A base perfeita para qualquer guarda-roupa. Peças atemporais e versáteis que combinam com absolutamente tudo, para facilitar o seu dia a dia.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784638353/basicos-essenciais-feminino_nevdfc.jpg', 'NEW_ARRIVALS', 3, 'WOMEN'),
('Streetwear Urban', 'streetwear-urban-4', 'Para quem dita as regras nas ruas. Modelagens amplas, conforto absoluto e uma atitude que não passa despercebida no cenário urbano.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784638354/streetwear-urban_umxaku.jpg', 'NEW_ARRIVALS', 4, 'WOMEN'),
('Flora', 'flora-5', 'Uma homenagem à beleza da natureza. Estampas exclusivas desenhadas à mão em tecidos leves e esvoaçantes que trazem leveza ao seu caminhar.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784638353/flora-feminino_zukpjp.jpg', 'FEATURED', 5, 'WOMEN'),
('TSM galeria', 'tsm-galeria-6', 'Onde a moda encontra a arte. Peças de vanguarda com cortes assimétricos e design inovador para quem ama exclusividade.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784653020/tsm-galeria-feminino_enm7lp.jpg', 'FEATURED', 6, 'WOMEN'),
-- Man collections
('Coleção Verão 26', 'colecao-verao-26-7', 'Prepare-se para os dias quentes com a nova linha masculina de Verão. Materiais respiráveis e cortes modernos que acompanham a sua rotina dinâmica.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784654178/ver%C3%A3o-26-masculino_vdf1g1.jpg', 'NEW_ARRIVALS', 7, 'MEN'),
('Essential Basics', 'essential-basics-8', 'O poder do simples. Camisetas, calças e bermudas essenciais que entregam durabilidade extrema e caimento impecável para todo momento.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784654175/basic-assentials-masculino_zlxaul.jpg', 'NEW_ARRIVALS', 8, 'MEN'),
('Inverno 26', 'inverno-26-9', 'Enfrente o frio com atitude. Jaquetas estruturadas, tricots luxuosos e uma paleta de cores sóbria para o inverno mais elegante da sua vida.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784654176/inverno-26-masculino_vgupma.jpg', 'FEATURED', 9, 'MEN'),
('Executive', 'Executive-10', 'A linha premium para o ambiente corporativo e ocasiões formais. Alfaiataria de ponta, tecidos importados e precisão em cada costura.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784654176/executive-masculino_jotw2b.jpg', 'FEATURED', 10, 'MEN'),
('Modern Gentleman', 'modern-gentleman-11', 'O encontro entre a tradição e o estilo contemporâneo. Uma coleção sofisticada para o homem moderno que valoriza detalhes refinados.', true, 'https://res.cloudinary.com/apgaq55g/image/upload/v1784654255/modern-men-masculino_vkyqfg.jpg', 'FEATURED', 11, 'MEN');